[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "onepiece"
version = "0.1.0"
description = "Open-source pipeline CLI toolkit"
authors = [{name="Jack Shortiss", email="jdshortiss@hotmail.com"}]
readme = "README.md"
requires-python = ">=3.9"

dependencies = [
    "typer>=0.10.0",
    "tqdm>=4.66.1",
    "structlog>=23.3.0",
    "av>=12.0"
]

[tool.setuptools.packages.find]
include = ["onepiece", "onepiece.*"]

[project.optional-dependencies]
dev = [
    "pytest>=8.0.0",
    "pytest-mock>=3.12.0",
    "black>=23.9.0",
    "isort>=6.12.0",
    "ruff>=0.0.321",
    "mypy>=1.4.0",
]

[tool.black]
line-length = 88

[tool.ruff]
select = ["E", "F"]
ignore = ["E501"]

[tool.mypy]
python_version = "3.11"

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]
