name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Create venv & install dependencies
        run: |
          python -m venv .venv
          .venv/bin/pip install -U pip
          # Core dev tools
          .venv/bin/pip install black ruff mypy pytest pre-commit
          # Stub packages for mypy
          .venv/bin/pip install types-requests types-PyYAML

      - name: Black check
        run: .venv/bin/black --check src

      - name: Ruff lint
        run: .venv/bin/ruff check src

      - name: Mypy type check
        run: .venv/bin/mypy src --strict

      - name: Run tests
        run: .venv/bin/pytest --maxfail=1 --disable-warnings -q

      - name: Pre-commit hooks
        run: .venv/bin/pre-commit run --all-files --show-diff-on-failure
