name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Create fresh venv & install dependencies
        run: |
          rm -rf .venv
          python -m venv .venv
          .venv/bin/pip install -U pip
          if [ -f requirements.txt ]; then .venv/bin/pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then .venv/bin/pip install -r requirements-dev.txt; fi
          .venv/bin/pip install .[dev]

      - name: Format check (Black + Ruff)
        run: make check-format

      - name: Lint check
        run: make lint

      - name: Type check
        run: make typecheck

      - name: Run tests
        run: make test

      - name: Pre-commit hooks
        run: .venv/bin/pre-commit run --all-files --show-diff-on-failure
